/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aave from "./aave";
export type { aave };
import type * as tokens from "./tokens";
export type { tokens };
export type { WETH9Mock } from "./WETH9Mock";
