/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Decimals__factory } from "./ERC20Decimals__factory";
export { USDT6__factory } from "./USDT6__factory";
